import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { LanguageProvider } from "@/context/LanguageContext";

const notoSans = Noto_Sans({
  subsets: ["bengali", "latin"],
  variable: "--font-noto-sans",
});

export const metadata = {
  title: "XYZ School & College",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="bn" className="bg-gray-50">
      <body
        className={`min-h-screen bg-gray-50 ${notoSans.variable} antialiased`}
      >
        <LanguageProvider>
          <nav className="px-[2%] xl:px-[14%]">
            <Navbar />
          </nav>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
