import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const notoSans = Noto_Sans({
  subsets: ["bengali", "latin"], // Bengali এবং Latin support
  variable: "--font-noto-sans",
});

export const metadata = {
  title: "XYZ School & College",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="bn" className="bg-[#fffdfd]">
      <body
        className={`min-h-screen bg-[#fffdfd] ${notoSans.variable} antialiased`}
      >
        <nav className="px-[2%] xl:px-[14%]">
          <Navbar />
        </nav>
        {children}
      </body>
    </html>
  );
}
